# Generated by Django 6.0.6 on 2026-07-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_img',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
    ]
