# Generated by Django 6.0.6 on 2026-07-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productvariant_variant_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
