# Generated by Django 6.0.6 on 2026-07-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
