# Generated by Django 6.0.6 on 2026-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderlineitem_img_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderitem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
