# Generated by Django 6.0.6 on 2026-07-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_orderitem_delete_orders_productvariant_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.godown'),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('from_godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='store.godown')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('to_godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='store.godown')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='store.godown')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godown_stocks', to='store.product')),
            ],
            options={
                'unique_together': {('godown', 'product')},
            },
        ),
        migrations.CreateModel(
            name='VariantStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_stocks', to='store.godown')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godown_stocks', to='store.productvariant')),
            ],
            options={
                'unique_together': {('godown', 'variant')},
            },
        ),
    ]
